language: cpp
dist: bionic

env:
  - CXX=g++-7 CC=gcc-7
  - CXX=g++-8 CC=gcc-8
  - CXX=g++-9 CC=gcc-9

install:
  - sudo apt -y remove cmake
#inside cmake
  - mkdir new-cmake && cd new-cmake
  - wget https://github.com/Kitware/CMake/releases/download/v3.17.3/cmake-3.17.3-Linux-x86_64.tar.gz
  - tar -zxf cmake-3.17.3-Linux-x86_64.tar.gz
  - export PATH=$PATH:$PWD/cmake-3.17.3-Linux-x86_64/bin
  - cmake --version
  - cd ..
# inside $HOME
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt -qy install $CXX $CC libpng-dev libjpeg-dev libtiff-dev libraw-dev libblas-dev liblapack-dev
  - sudo snap install cmake --classic
  - cmake --version
  - mkdir 3rdparty
  - cd 3rdparty
#inside 3rdparty
  - wget https://dl.bintray.com/boostorg/release/1.73.0/source/boost_1_73_0.tar.gz
  - tar -xzf boost_1_73_0.tar.gz
  - cd boost_1_73_0
#inside 3rdparty/boost_1_73_0
  - ./bootstrap.sh
  - ./b2 --with-filesystem
  - export BOOST_ROOT=$PWD
  - echo $BOOST_ROOT
  - cd ../
#inside 3rdparty
  - git clone https://bitbucket.org/blaze-lib/blaze.git
  - cd blaze
#inside 3rdparty/blaze
  - mkdir build && cd build
  - cmake ..
  - sudo make install
  - cd ../../..
  - ls
  - mkdir build && cd build
  - cmake ..
