language: cpp
dist: bionic

install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt -qy install g++-8 g++-9 libpng-dev libjpeg-dev libtiff-dev libraw-dev libblas-dev
  - sudo snap install cmake --classic
  - mkdir 3rdparty
  - cd 3rdparty
#inside 3rdparty
  - wget https://dl.bintray.com/boostorg/release/1.73.0/source/boost_1_73_0.tar.gz
  - tar -xzf boost_1_73_0.tar.gz
  - cd boost_1_73_0
#inside 3rdparty/boost_1_73_0
  - ./bootstrap.sh
  - ./b2 --with-filesystem
  - export BOOST_ROOT=$PWD
  - echo $BOOST_ROOT
  - cd ../
#inside 3rdparty
  - git clone https://bitbucket.org/blaze-lib/blaze.git
  - cd blaze
#inside 3rdparty/blaze
  - mkdir build && cd build
  - cmake ..
  - sudo make install
  - cd ../../..
  - ls
  - mkdir build && cd build
  - cmake ..
