language: cpp

install:
  - mkdir 3rdparty
  - cd 3rdparty
#inside 3rdparty directory
  - wget https://dl.bintray.com/boostorg/release/1.73.0/source/boost_1_73_0.tar.gz
  - tar -xzf boost_1_73_0.tar.gz
  - cd boost_1_73_0
#inside 3rdparty/boost_1_73_0
  - ./bootstrap.sh
  - ./b2 --with-filesystem
