language: cpp
dist: bionic

install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt -y install g++-8 g++-9
  - sudo snap install cmake
  - mkdir 3rdparty
  - cd 3rdparty
#inside 3rdparty
  - wget https://dl.bintray.com/boostorg/release/1.73.0/source/boost_1_73_0.tar.gz
  - tar -xzf boost_1_73_0.tar.gz
  - cd boost_1_73_0
#inside 3rdparty/boost_1_73_0
  - ./bootstrap.sh
  - ./b2 --with-filesystem
  - cd ../
#inside 3rdparty
  - git clone https://bitbucket.org/blaze-lib/blaze.git